version: '3.3'
services:
  db:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_DATABASE: 'hack_climate_change_2020'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      SECURE-FILE-PRIV: ''
    ports:
      - '13306:3306'
    expose:
      - '3306'
    volumes:
      - ./config:/docker-entrypoint-initdb.d

volumes:
  db_data: